SELECT  TOP 10 * FROM customers;
-- Business Questions :

-- Q1. What are the total revenue generated by Male vs Female Customers :
SELECT 
	Gender,
	SUM(Purchase_Amount) AS Total_Revenue
FROM customers
GROUP BY Gender;

-- Q2. Which Customer used a discount  but still spend mre than average purchase amount :
SELECT 
	Customer_ID,
	Purchase_Amount
FROM customers
WHERE Discount_Applied = 'Yes' AND Purchase_Amount >= (SELECT AVG(Purchase_Amount) FROM customers)
ORDER BY Purchase_Amount DESC;

-- Q3. Which are the Top 5 Products with the highest Average Review Rating :
SELECT TOP 5
	Item_Purchased,
	ROUND(AVG(Review_Rating),2) Avg_Review_Rating
FROM customers
GROUP BY Item_Purchased
ORDER BY Avg_Review_Rating DESC 

-- Q4. Compare the Average Purchase Amount between  Standard and Express shipping :
SELECT 
	Shipping_Type,
	AVG(Purchase_Amount) AS Avg_Purchase
FROM customers
WHERE Shipping_Type IN('Standard','Express')
GROUP BY Shipping_Type

-- Q5. Do subscribed customers spend more ? Compare average spend and total revenue between Subscribers and Non subscribers :
SELECT 
	Subscription_Status,
	COUNT(*) AS Total_Customer,
	AVG(Purchase_Amount) Avg_purchase,
	SUM(Purchase_Amount) Total_Revenue
FROM customers
GROUP BY Subscription_Status 
 
 -- Q6. Which 5 Products have the highest percentage of purchase with Discount applied :
 SELECT TOP 5
	Item_Purchased,
	ROUND(CAST(SUM(CASE WHEN Discount_Applied ='Yes' THEN 1 ELSE 0 END ) AS FLOAT) / COUNT(*) *100 ,2) AS Discount_Rate
 FROM customers
 GROUP BY Item_Purchased
 ORDER BY Discount_Rate DESC

 --Q7. Segment the Customers into New, Returning, Loyal based on their total number of Previous  Purchase & show count of each segment :
 WITH Customer_Types AS
 (SELECT 
	 Customer_ID,
	 Previous_Purchases,
	 CASE 
		WHEN Previous_Purchases = 1 THEN 'New'
		WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS Customer_Segment
 FROM customers
 )
 SELECT 
	Customer_Segment,
	COUNT(*)  AS Total_Customer
 FROM Customer_Types
 GROUP BY Customer_Segment
 ORDER BY Total_Customer DESC

 -- Q8. What are the Top 3 most Purchase Product within each Category :
WITH Item_Counts AS
(SELECT 
	Category,
	Item_Purchased,
	COUNT(*) AS Total_Customer,
	ROW_NUMBER() OVER(PARTITION BY Category ORDER BY COUNT(*) DESC) AS Ranked
FROM customers
GROUP BY Category,Item_Purchased
)
SELECT
	Ranked,
	Category,
	Item_Purchased,Total_Customer
FROM Item_Counts
WHERE Ranked <=3;

-- Q9. Are Customers who are repeat buyers (More than 5 Previous Purchases) also likely to subscribe :
SELECT 
	Subscription_Status,
	COUNT(*) AS Total_buyers
FROM customers
WHERE Previous_Purchases >5
GROUP BY Subscription_Status

-- Q10. What is the Revenue Contribution of each Age Group :
SELECT 
	Age_Groups,
	SUM(Purchase_Amount) AS Revenue_Contribution
FROM customers
GROUP BY Age_Groups
ORDER BY Revenue_Contribution DESC